[tool.poetry]
name = "arcgis2geojson"
version = "2.0.1"
description = "A Python library for converting ArcGIS JSON to GeoJSON"
authors = ["chris48s"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chris48s/arcgis2geojson"
homepage = "https://github.com/chris48s/arcgis2geojson"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
coverage = "^6.0"
isort = { version = "^5.8", python = "^3.6.2" }
flake8 = "^3.9.2"
black = { version = "==21.9b0", allow-prereleases = true, python = "^3.6.2" }

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
arcgis2geojson = 'arcgis2geojson:main'
