name: Publish
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get python versions
        uses: chris48s/satisfying-python@main
        id: python-versions

      - name: Build, Test, Lint
        uses: chris48s/python-package-shared@main
        with:
          python-version: '${{ steps.python-versions.outputs.min }}'
          pre-install: poetry

      - uses: actions/upload-artifact@v7
        with:
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    permissions:
      contents: none
      id-token: write # required for trusted publishing
    environment: publish
    steps:
      - uses: actions/download-artifact@v7

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
          print-hash: true
